version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: todo-app-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: todo_app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: todo_user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 